export const heroes = [
  "avengers",
  "superman",
  "spider-man",
  "ironman",
  "black panther",
  "Deadpool",
  "CAPTAIN AMERICA",
  "JESSICA JONES",
  "antman",
  "captain marvel",
  "GUARDIANS OF THE GALAXY",
  "WOLVERINE",
  "luke cage",
];
